artifact_location: file:///C:/Users/Samuel%20Santos/Documents/MDSAA-DS/MLOPS/GitHub/MLOPS/mlflow_project/ml_artifacts/0
creation_time: 1687771546859
experiment_id: '0'
last_update_time: 1687771546859
lifecycle_stage: active
name: Default
